from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("http://practice.automationtesting.in")
time.sleep(1)
shop_btn = driver.find_element_by_css_selector('#menu-item-40 > a')
shop_btn.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,300);")
add_HTML_to_cart = driver.find_element_by_css_selector('[data-product_id="182"]')
add_HTML_to_cart.click()
time.sleep(1)
cart_btn = driver.find_element_by_class_name('wpmenucart-contents')
cart_btn.click()
time.sleep(2)
proceed_btn = WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.CLASS_NAME,'wc-forward')))
proceed_btn.click()
driver.execute_script("window.scrollBy(0,300);")
first_name = WebDriverWait(driver,5).until(EC.element_to_be_clickable((By.ID,'billing_first_name')))
first_name.send_keys('Roy')
last_name = driver.find_element_by_id('billing_last_name')
last_name.send_keys('Orbison')
email = driver.find_element_by_id('billing_email')
email.send_keys('rorb@example.com')
phone = driver.find_element_by_id('billing_phone')
phone.send_keys('+21567896')
country_selector = driver.find_element_by_id('s2id_billing_country')
country_selector.click()
country_input = driver.find_element_by_id('s2id_autogen1_search')
country_input.send_keys('Russia')
time.sleep(1)
russia_select = driver.find_element_by_class_name('select2-match')
russia_select.click()
time.sleep(1)
address = driver.find_element_by_id('billing_address_1')
address.send_keys('Petrovka str., 38')
city = driver.find_element_by_id('billing_city')
city.send_keys('Saint-Petersburg')
state = driver.find_element_by_id('billing_state')
state.send_keys('Saint-Petersburg')
postcode = driver.find_element_by_id('billing_postcode')
postcode.send_keys('190000')
driver.execute_script("window.scrollBy(0,600);")
check_payment = driver.find_element_by_id('payment_method_cheque')
check_payment.click()
place_order_btn = driver.find_element_by_id('place_order')
place_order_btn.click()
time.sleep(2)
thanks_message = WebDriverWait(driver,5).until(EC.text_to_be_present_in_element((By.CLASS_NAME,'woocommerce-thankyou-order-received'), 'Thank you. Your order has been received.'))
pay_method = WebDriverWait(driver,5).until(EC.text_to_be_present_in_element((By.CSS_SELECTOR,'tfoot > tr:nth-child(3) > td'), 'Check Payments'))
time.sleep(2)
driver.quit()
